baseURL = 'https://blog.pvizc.cc/'
languageCode = 'es'
title = 'Entropía Razonada'
theme = 'hugo-theme-nostyleplease'
enableRobotsTXT = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  subtitle = 'Apuntes incompletos sobre tecnología, economía y sentido en la era de la máquina.'
  
[markup.goldmark.renderer]
  unsafe = true
  
[menu]
  [[menu.main]]
    name = "Inicio"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Sobre mí"
    url = "/sobre-mi/"
    weight = 3
  [[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 4
